#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
TOTAL_STAGES=6

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
TABLE="$REPO_ROOT/data/game-fingerprints.json"
APP_ID=674940

detect_game_dir() {
  local steam vdf lib acf dir
  steam="$(reg query "HKCU\\SOFTWARE\\Valve\\Steam" //v SteamPath 2>/dev/null | grep -oE '[A-Za-z]:[^ ]*' | head -1)"
  [ -n "$steam" ] || return 1
  vdf="$steam/steamapps/libraryfolders.vdf"
  [ -f "$vdf" ] || return 1
  while IFS= read -r lib; do
    lib="$(printf '%s' "$lib" | sed 's/\\\\/\\/g')"
    acf="$lib/steamapps/appmanifest_$APP_ID.acf"
    [ -f "$acf" ] || continue
    dir="$(grep -i '"installdir"' "$acf" | sed 's/.*"\(.*\)".*/\1/')"
    [ -n "$dir" ] && { printf '%s/steamapps/common/%s' "$lib" "$dir"; return 0; }
  done < <(grep -i '"path"' "$vdf" | sed 's/.*"\(.*\)".*/\1/')
  return 1
}

banner "Stick Fight 官方构建指纹表"

stage "这一步在做什么"
say "Lunaqua 判断玩家游戏文件干不干净，靠三样：appmanifest 的 buildid、官方构建指纹表、本机首扫基线。"
say "这一趟就是把「官方构建指纹表」做出来：每个官方 build 一行，记录 buildid + 关键文件 SHA-256。"
note "关键文件：StickFight.exe、StickFight_Data/Managed/Assembly-CSharp.dll、UnityEngine.dll、globalgamemanagers"
say ""
step "当前 build：走「Steam 校验 + 本机采集」，不用登录，几分钟"
step "历史 build（可选）：走 DepotDownloader，需要你的 Steam 账号；密码和 2FA 由它自己问，本向导不碰"
pause "明白了，开始"

stage "抓当前 build 的 depot / manifest"
say "从公开镜像 api.steamcmd.net 读 AppID 674940 的当前构建信息（匿名，不需要账号）。"
API="$(mktemp)"
curl -fsS --max-time 30 "https://api.steamcmd.net/v1/info/$APP_ID" -o "$API"
API_WIN="$(cygpath -w "$API" 2>/dev/null || printf '%s' "$API")"
BUILD_ID="$(node -e 'const j=require(process.argv[1]).data[process.argv[2]];console.log(j.depots.branches.public.buildid)' "$API_WIN" "$APP_ID")"
read -r DEPOT MANIFEST <<<"$(node -e '
const app = require(process.argv[1]).data[process.argv[2]];
const rows = [];
for (const [id, d] of Object.entries(app.depots)) {
  if (id === "branches") continue;
  const cfg = d.config || {};
  if ((cfg.oslist || "") !== "windows") continue;
  rows.push([Number(id), ((d.manifests || {}).public || {}).gid || ""]);
}
rows.sort((a, b) => b[0] - a[0]);
console.log(rows.length ? rows[0][0] + " " + rows[0][1] : "");
' "$API_WIN" "$APP_ID")"
say ""
printf '  %s当前 buildid：%s%s\n' "$BOLD" "$BUILD_ID" "$RESET"
printf '  %sWindows depot：%s   manifest：%s%s\n' "$BOLD" "$DEPOT" "$MANIFEST" "$RESET"
pause "记下了，继续"

stage "把本机游戏还原成官方文件"
warn "这一步会调用 Steam 校验：被改过的游戏文件会被还原"
note "BepInEx 的 winhttp.dll / BepInEx 目录不在官方清单里，校验不会动它们"
say ""
step "你 Managed 目录里手改的 Assembly-CSharp.dll.* 副本会被同名官方文件覆盖，先确认不再需要它们"
if confirm "现在打开 Steam 校验（steam://validate/$APP_ID）？"; then
  open_url "steam://validate/$APP_ID"
  step "在 Steam 里等「验证游戏文件的完整性」跑完"
  pause "校验完成后按回车"
else
  warn "跳过校验：采到的哈希可能不是官方的，别把这一行提交进表"
fi

stage "采集指纹并写入表"
DETECTED="$(detect_game_dir || true)"
if [ -n "$DETECTED" ]; then
  note "自动探测到：$DETECTED"
fi
ask GAME_DIR "游戏目录（含 StickFight.exe）:"
if [ -z "$GAME_DIR" ]; then GAME_DIR="$DETECTED"; fi
if [ -n "$GAME_DIR" ]; then
  ROW="$(mktemp)"
  bash "$SCRIPT_DIR/capture-fingerprint.sh" "$GAME_DIR" "$BUILD_ID" "$DEPOT" "$MANIFEST" "$ROW"
  say ""
  cat "$ROW"
  say ""
  node "$SCRIPT_DIR/merge-fingerprint.mjs" "$TABLE" "$ROW"
else
  warn "没有可用目录，这一步没做"
fi

stage "历史 build（可选）"
say "SteamDB 能免费浏览这个 depot 的历史 manifest 列表。"
open_url "https://steamdb.info/depot/$DEPOT/manifests/"
say ""
if ! command -v DepotDownloader >/dev/null 2>&1; then
  warn "没装 DepotDownloader，跳过历史 build"
  note "想补历史：winget install --exact --id SteamRE.DepotDownloader，然后重跑本向导"
else
  ask STEAM_USER "Steam 用户名（密码/2FA 由 DepotDownloader 自己问）:"
  while confirm "要加一个历史 build 吗？"; do
    ask HIST_BUILD_ID "这个 manifest 对应的 buildid（SteamDB 同一行）:"
    ask HIST_MANIFEST "manifest id（SteamDB 那一行）:"
    OUT_DIR="$HOME/.lunaqua-fingerprint/$HIST_MANIFEST"
    mkdir -p "$OUT_DIR"
    printf 'regex:(?i)(StickFight(TheGame)?\\.exe|Managed/Assembly-CSharp\\.dll|Managed/UnityEngine\\.dll|globalgamemanagers)$\n' > "$OUT_DIR/filelist.txt"
    say "只拉几个文件，几 MB 而已……"
    if DepotDownloader -app "$APP_ID" -depot "$DEPOT" -manifest "$HIST_MANIFEST" -filelist "$OUT_DIR/filelist.txt" -username "$STEAM_USER" -dir "$OUT_DIR/files"; then
      ROW="$(mktemp)"
      bash "$SCRIPT_DIR/capture-fingerprint.sh" "$OUT_DIR/files" "$HIST_BUILD_ID" "$DEPOT" "$HIST_MANIFEST" "$ROW"
      node "$SCRIPT_DIR/merge-fingerprint.mjs" "$TABLE" "$ROW"
    else
      warn "下载失败（旧 manifest 常常已经 401），换一个再试"
    fi
  done
fi

stage "收尾"
COUNT="$(node -e 'const t=require(process.argv[1]);console.log((t.builds||[]).length)' "$(cygpath -w "$TABLE" 2>/dev/null || printf '%s' "$TABLE")" 2>/dev/null || echo '?')"
printf '  %s✓ 指纹表现在有 %s 个 build%s\n' "$GREEN" "$COUNT" "$RESET"
say "文件：$TABLE"
step "提交它（或告诉 agent 已经生成好了，让它接上 M3 的干净判定）"
note "游戏每次大更新后，重跑本向导补新 build"

finish
